name: Pull Requests

on:
  pull_request:
    branches:
        - main
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
    steps:
      - uses: actions/checkout@v3

      - name: sccache
        run: |
          sccache --zero-stats

      - name: Build and Test
        uses: llvm/actions/build-test-llvm-project@main
        env:
          CC: "clang"
          CXX: "clang++"
          LD: "LLD"
        with:
          cmake_args: '-GNinja -DLLVM_ENABLE_PROJECTS="llvm" -DCMAKE_BUILD_TYPE=Release -DLLDB_INCLUDE_TESTS=OFF -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache'
          build_target: 'check-all'

      - name: sccache stats
        run: |
          sccache --show-stats


